name: format

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    if: github.actor != 'github-actions[bot]' # Avoid infinite loops

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format code
        run: pnpm exec prettier -w .

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore(format): auto-format files"
            git fetch origin main
            git rebase origin/main
            git push
          fi
